# Generated by Django 4.1.5 on 2023-01-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='is_student',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='user_type',
            old_name='is_teach',
            new_name='is_user',
        ),
    ]
