# Generated by Django 4.1.5 on 2023-03-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0009_alter_report_user_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hardness', models.IntegerField()),
                ('TDS', models.IntegerField()),
                ('chloramines', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sulfate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('conductivity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('organic_carbon', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trihalomethanes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('turbidity', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
