# Generated by Django 4.1.5 on 2023-03-11 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0010_waterquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterquality',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
