# Generated by Django 4.1.5 on 2023-03-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0011_waterquality_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='waterquality',
            name='company',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
