# Generated by Django 4.1.5 on 2023-03-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0012_alter_report_options_waterquality_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='company',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
