# Generated by Django 4.1.5 on 2023-03-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0015_alter_waterquality_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterquality',
            name='company',
        ),
    ]
