# Generated by Django 4.1.5 on 2023-03-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basewater', '0017_waterquality_company'),
    ]

    operations = [
    ]
